/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EscrowVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createOrder"
      | "getOrder"
      | "markDelivered"
      | "orderCount"
      | "orders"
      | "platformWallet"
      | "refund"
      | "release"
      | "submitVerification"
      | "usdcToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OrderCreated"
      | "OrderDelivered"
      | "OrderRefunded"
      | "OrderReleased"
      | "VerificationSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createOrder",
    values: [
      BigNumberish,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "markDelivered",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "orderCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "orders",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "platformWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "refund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "release",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitVerification",
    values: [BigNumberish, BytesLike, boolean]
  ): string;
  encodeFunctionData(functionFragment: "usdcToken", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "createOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOrder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "markDelivered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "orderCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "orders", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "release", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdcToken", data: BytesLike): Result;
}

export namespace OrderCreatedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    productId: BigNumberish,
    buyer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    productId: bigint,
    buyer: string,
    amount: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    productId: bigint;
    buyer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderDeliveredEvent {
  export type InputTuple = [orderId: BigNumberish, deliverProofHash: BytesLike];
  export type OutputTuple = [orderId: bigint, deliverProofHash: string];
  export interface OutputObject {
    orderId: bigint;
    deliverProofHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderRefundedEvent {
  export type InputTuple = [orderId: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [orderId: bigint, amount: bigint];
  export interface OutputObject {
    orderId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderReleasedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    merchantAmount: BigNumberish,
    platformFee: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    merchantAmount: bigint,
    platformFee: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    merchantAmount: bigint;
    platformFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationSubmittedEvent {
  export type InputTuple = [orderId: BigNumberish, passed: boolean];
  export type OutputTuple = [orderId: bigint, passed: boolean];
  export interface OutputObject {
    orderId: bigint;
    passed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EscrowVault extends BaseContract {
  connect(runner?: ContractRunner | null): EscrowVault;
  waitForDeployment(): Promise<this>;

  interface: EscrowVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createOrder: TypedContractMethod<
    [
      productId: BigNumberish,
      buyer: AddressLike,
      merchant: AddressLike,
      amount: BigNumberish,
      timeout: BigNumberish,
      paymentProofHash: BytesLike,
      requiresVerification: boolean
    ],
    [bigint],
    "nonpayable"
  >;

  getOrder: TypedContractMethod<
    [orderId: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        boolean,
        boolean,
        boolean,
        boolean
      ] & {
        productId: bigint;
        buyer: string;
        merchant: string;
        amount: bigint;
        createdAt: bigint;
        delivered: boolean;
        verified: boolean;
        released: boolean;
        refunded: boolean;
      }
    ],
    "view"
  >;

  markDelivered: TypedContractMethod<
    [orderId: BigNumberish, deliverProofHash: BytesLike],
    [void],
    "nonpayable"
  >;

  orderCount: TypedContractMethod<[], [bigint], "view">;

  orders: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        boolean,
        boolean,
        string,
        string,
        boolean
      ] & {
        productId: bigint;
        buyer: string;
        merchant: string;
        amount: bigint;
        createdAt: bigint;
        timeout: bigint;
        delivered: boolean;
        verified: boolean;
        released: boolean;
        refunded: boolean;
        paymentProofHash: string;
        deliverProofHash: string;
        requiresVerification: boolean;
      }
    ],
    "view"
  >;

  platformWallet: TypedContractMethod<[], [string], "view">;

  refund: TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;

  release: TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;

  submitVerification: TypedContractMethod<
    [orderId: BigNumberish, resultHash: BytesLike, passed: boolean],
    [void],
    "nonpayable"
  >;

  usdcToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createOrder"
  ): TypedContractMethod<
    [
      productId: BigNumberish,
      buyer: AddressLike,
      merchant: AddressLike,
      amount: BigNumberish,
      timeout: BigNumberish,
      paymentProofHash: BytesLike,
      requiresVerification: boolean
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getOrder"
  ): TypedContractMethod<
    [orderId: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        boolean,
        boolean,
        boolean,
        boolean
      ] & {
        productId: bigint;
        buyer: string;
        merchant: string;
        amount: bigint;
        createdAt: bigint;
        delivered: boolean;
        verified: boolean;
        released: boolean;
        refunded: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "markDelivered"
  ): TypedContractMethod<
    [orderId: BigNumberish, deliverProofHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "orderCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "orders"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        boolean,
        boolean,
        string,
        string,
        boolean
      ] & {
        productId: bigint;
        buyer: string;
        merchant: string;
        amount: bigint;
        createdAt: bigint;
        timeout: bigint;
        delivered: boolean;
        verified: boolean;
        released: boolean;
        refunded: boolean;
        paymentProofHash: string;
        deliverProofHash: string;
        requiresVerification: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "platformWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "release"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitVerification"
  ): TypedContractMethod<
    [orderId: BigNumberish, resultHash: BytesLike, passed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "usdcToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "OrderCreated"
  ): TypedContractEvent<
    OrderCreatedEvent.InputTuple,
    OrderCreatedEvent.OutputTuple,
    OrderCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OrderDelivered"
  ): TypedContractEvent<
    OrderDeliveredEvent.InputTuple,
    OrderDeliveredEvent.OutputTuple,
    OrderDeliveredEvent.OutputObject
  >;
  getEvent(
    key: "OrderRefunded"
  ): TypedContractEvent<
    OrderRefundedEvent.InputTuple,
    OrderRefundedEvent.OutputTuple,
    OrderRefundedEvent.OutputObject
  >;
  getEvent(
    key: "OrderReleased"
  ): TypedContractEvent<
    OrderReleasedEvent.InputTuple,
    OrderReleasedEvent.OutputTuple,
    OrderReleasedEvent.OutputObject
  >;
  getEvent(
    key: "VerificationSubmitted"
  ): TypedContractEvent<
    VerificationSubmittedEvent.InputTuple,
    VerificationSubmittedEvent.OutputTuple,
    VerificationSubmittedEvent.OutputObject
  >;

  filters: {
    "OrderCreated(uint256,uint256,address,uint256)": TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;
    OrderCreated: TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;

    "OrderDelivered(uint256,bytes32)": TypedContractEvent<
      OrderDeliveredEvent.InputTuple,
      OrderDeliveredEvent.OutputTuple,
      OrderDeliveredEvent.OutputObject
    >;
    OrderDelivered: TypedContractEvent<
      OrderDeliveredEvent.InputTuple,
      OrderDeliveredEvent.OutputTuple,
      OrderDeliveredEvent.OutputObject
    >;

    "OrderRefunded(uint256,uint256)": TypedContractEvent<
      OrderRefundedEvent.InputTuple,
      OrderRefundedEvent.OutputTuple,
      OrderRefundedEvent.OutputObject
    >;
    OrderRefunded: TypedContractEvent<
      OrderRefundedEvent.InputTuple,
      OrderRefundedEvent.OutputTuple,
      OrderRefundedEvent.OutputObject
    >;

    "OrderReleased(uint256,uint256,uint256)": TypedContractEvent<
      OrderReleasedEvent.InputTuple,
      OrderReleasedEvent.OutputTuple,
      OrderReleasedEvent.OutputObject
    >;
    OrderReleased: TypedContractEvent<
      OrderReleasedEvent.InputTuple,
      OrderReleasedEvent.OutputTuple,
      OrderReleasedEvent.OutputObject
    >;

    "VerificationSubmitted(uint256,bool)": TypedContractEvent<
      VerificationSubmittedEvent.InputTuple,
      VerificationSubmittedEvent.OutputTuple,
      VerificationSubmittedEvent.OutputObject
    >;
    VerificationSubmitted: TypedContractEvent<
      VerificationSubmittedEvent.InputTuple,
      VerificationSubmittedEvent.OutputTuple,
      VerificationSubmittedEvent.OutputObject
    >;
  };
}
