/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ProductRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createProduct"
      | "getProduct"
      | "productCount"
      | "products"
      | "setActive"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ProductCreated" | "ProductUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createProduct",
    values: [BigNumberish, BigNumberish, BigNumberish, boolean, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProduct",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "productCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "products",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setActive",
    values: [BigNumberish, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "createProduct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getProduct", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "productCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "products", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setActive", data: BytesLike): Result;
}

export namespace ProductCreatedEvent {
  export type InputTuple = [
    productId: BigNumberish,
    merchant: AddressLike,
    price: BigNumberish,
    requiresVerification: boolean
  ];
  export type OutputTuple = [
    productId: bigint,
    merchant: string,
    price: bigint,
    requiresVerification: boolean
  ];
  export interface OutputObject {
    productId: bigint;
    merchant: string;
    price: bigint;
    requiresVerification: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProductUpdatedEvent {
  export type InputTuple = [productId: BigNumberish, active: boolean];
  export type OutputTuple = [productId: bigint, active: boolean];
  export interface OutputObject {
    productId: bigint;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProductRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ProductRegistry;
  waitForDeployment(): Promise<this>;

  interface: ProductRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createProduct: TypedContractMethod<
    [
      price: BigNumberish,
      platformFeeBps: BigNumberish,
      deliveryTimeout: BigNumberish,
      requiresVerification: boolean,
      metadataHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  getProduct: TypedContractMethod<
    [productId: BigNumberish],
    [
      [string, bigint, bigint, bigint, boolean, string, boolean] & {
        merchant: string;
        price: bigint;
        platformFeeBps: bigint;
        deliveryTimeout: bigint;
        requiresVerification: boolean;
        metadataHash: string;
        active: boolean;
      }
    ],
    "view"
  >;

  productCount: TypedContractMethod<[], [bigint], "view">;

  products: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, boolean, string, boolean] & {
        merchant: string;
        price: bigint;
        platformFeeBps: bigint;
        deliveryTimeout: bigint;
        requiresVerification: boolean;
        metadataHash: string;
        active: boolean;
      }
    ],
    "view"
  >;

  setActive: TypedContractMethod<
    [productId: BigNumberish, active: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createProduct"
  ): TypedContractMethod<
    [
      price: BigNumberish,
      platformFeeBps: BigNumberish,
      deliveryTimeout: BigNumberish,
      requiresVerification: boolean,
      metadataHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getProduct"
  ): TypedContractMethod<
    [productId: BigNumberish],
    [
      [string, bigint, bigint, bigint, boolean, string, boolean] & {
        merchant: string;
        price: bigint;
        platformFeeBps: bigint;
        deliveryTimeout: bigint;
        requiresVerification: boolean;
        metadataHash: string;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "productCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "products"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, boolean, string, boolean] & {
        merchant: string;
        price: bigint;
        platformFeeBps: bigint;
        deliveryTimeout: bigint;
        requiresVerification: boolean;
        metadataHash: string;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setActive"
  ): TypedContractMethod<
    [productId: BigNumberish, active: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ProductCreated"
  ): TypedContractEvent<
    ProductCreatedEvent.InputTuple,
    ProductCreatedEvent.OutputTuple,
    ProductCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ProductUpdated"
  ): TypedContractEvent<
    ProductUpdatedEvent.InputTuple,
    ProductUpdatedEvent.OutputTuple,
    ProductUpdatedEvent.OutputObject
  >;

  filters: {
    "ProductCreated(uint256,address,uint256,bool)": TypedContractEvent<
      ProductCreatedEvent.InputTuple,
      ProductCreatedEvent.OutputTuple,
      ProductCreatedEvent.OutputObject
    >;
    ProductCreated: TypedContractEvent<
      ProductCreatedEvent.InputTuple,
      ProductCreatedEvent.OutputTuple,
      ProductCreatedEvent.OutputObject
    >;

    "ProductUpdated(uint256,bool)": TypedContractEvent<
      ProductUpdatedEvent.InputTuple,
      ProductUpdatedEvent.OutputTuple,
      ProductUpdatedEvent.OutputObject
    >;
    ProductUpdated: TypedContractEvent<
      ProductUpdatedEvent.InputTuple,
      ProductUpdatedEvent.OutputTuple,
      ProductUpdatedEvent.OutputObject
    >;
  };
}
