/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ReceiptRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getReceipt"
      | "receiptCount"
      | "receiptExists"
      | "receipts"
      | "recordReceipt"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ReceiptRecorded"): EventFragment;

  encodeFunctionData(
    functionFragment: "getReceipt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "receiptCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "receiptExists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "receipts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordReceipt",
    values: [BigNumberish, AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getReceipt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "receiptCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiptExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "receipts", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordReceipt",
    data: BytesLike
  ): Result;
}

export namespace ReceiptRecordedEvent {
  export type InputTuple = [
    receiptId: BigNumberish,
    orderId: BigNumberish,
    buyer: AddressLike,
    merchant: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    receiptId: bigint,
    orderId: bigint,
    buyer: string,
    merchant: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    receiptId: bigint;
    orderId: bigint;
    buyer: string;
    merchant: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReceiptRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ReceiptRegistry;
  waitForDeployment(): Promise<this>;

  interface: ReceiptRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getReceipt: TypedContractMethod<
    [receiptId: BigNumberish],
    [
      [bigint, string, string, bigint, bigint] & {
        orderId: bigint;
        buyer: string;
        merchant: string;
        amount: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  receiptCount: TypedContractMethod<[], [bigint], "view">;

  receiptExists: TypedContractMethod<
    [receiptId: BigNumberish],
    [boolean],
    "view"
  >;

  receipts: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, boolean] & {
        orderId: bigint;
        buyer: string;
        merchant: string;
        amount: bigint;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  recordReceipt: TypedContractMethod<
    [
      orderId: BigNumberish,
      buyer: AddressLike,
      merchant: AddressLike,
      amount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getReceipt"
  ): TypedContractMethod<
    [receiptId: BigNumberish],
    [
      [bigint, string, string, bigint, bigint] & {
        orderId: bigint;
        buyer: string;
        merchant: string;
        amount: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "receiptCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "receiptExists"
  ): TypedContractMethod<[receiptId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "receipts"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, boolean] & {
        orderId: bigint;
        buyer: string;
        merchant: string;
        amount: bigint;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordReceipt"
  ): TypedContractMethod<
    [
      orderId: BigNumberish,
      buyer: AddressLike,
      merchant: AddressLike,
      amount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "ReceiptRecorded"
  ): TypedContractEvent<
    ReceiptRecordedEvent.InputTuple,
    ReceiptRecordedEvent.OutputTuple,
    ReceiptRecordedEvent.OutputObject
  >;

  filters: {
    "ReceiptRecorded(uint256,uint256,address,address,uint256,uint256)": TypedContractEvent<
      ReceiptRecordedEvent.InputTuple,
      ReceiptRecordedEvent.OutputTuple,
      ReceiptRecordedEvent.OutputObject
    >;
    ReceiptRecorded: TypedContractEvent<
      ReceiptRecordedEvent.InputTuple,
      ReceiptRecordedEvent.OutputTuple,
      ReceiptRecordedEvent.OutputObject
    >;
  };
}
